import { SUPPORTED_CHAIN_CHECK_METHODS } from './checks';
import { GENERATED_ZOD_OBJECT_METHODS, GENERATED_ZOD_TYPE_METHODS } from './generated-zod-metadata';

export const ZOD_MINI_METHODS: Record<string, string> = {
  min: 'minLength',
  max: 'maxLength',
  step: 'multipleOf',
  or: 'union',
  and: 'intersection',
  default: '_default',
};

export const BASE_METHODS = [
  'string',
  'stringbool',
  'number',
  'bigint',
  'boolean',
  'symbol',
  'object',
  'looseObject',
  'strictObject',
  'array',
  'pipe',
  'literal',
  'enum',
  'nativeEnum',
  'union',
  'intersection',
  'record',
  'map',
  'set',
  'tuple',
  'promise',
  'date',
  'undefined',
  'null',
  'void',
  'any',
  'unknown',
  'never',
  'nan',
  'email',
  'url',
  'ipv4',
  'ipv6',
  'discriminatedUnion',
  'optional',
  'nullable',
  'nullish',
  '_default',
  'prefault',
  'catch',
  'catchall',
  'partial',
  'required',
  'readonly',
  'extend',
  'omit',
  'pick',
  'uuid',
  'int',
  'hash',
  'jwt',
  'xor',
];

export const PASSTHROUGH_BASE_METHODS = [
  '_function',
  'base64',
  'base64url',
  'cidrv4',
  'cidrv6',
  'clone',
  'codec',
  'config',
  'cuid',
  'cuid2',
  'custom',
  'decode',
  'decodeAsync',
  'e164',
  'emoji',
  'encode',
  'encodeAsync',
  'exactOptional',
  'file',
  'flattenError',
  'float32',
  'float64',
  'formatError',
  'function',
  'guid',
  'hex',
  'hostname',
  'httpUrl',
  'instanceof',
  'int32',
  'int64',
  'invertCodec',
  'json',
  'keyof',
  'ksuid',
  'lazy',
  'looseRecord',
  'mac',
  'merge',
  'nanoid',
  'nonoptional',
  'parse',
  'parseAsync',
  'partialRecord',
  'prettifyError',
  'preprocess',
  'registry',
  'safeDecode',
  'safeDecodeAsync',
  'safeEncode',
  'safeEncodeAsync',
  'safeExtend',
  'safeParse',
  'safeParseAsync',
  'stringFormat',
  'success',
  'iso',
  'time',
  'datetime',
  'duration',
  'templateLiteral',
  'toJSONSchema',
  'treeifyError',
  'uint32',
  'uint64',
  'ulid',
  'uuidv4',
  'uuidv6',
  'uuidv7',
  'xid',
];

const NON_WRAPPER_SCHEMA_METHODS = new Set([
  'apply',
  'check',
  'clone',
  'exactOptional',
  'isNullable',
  'isOptional',
  'keyof',
  'merge',
  'nonoptional',
  'passthrough',
  'register',
  'safeExtend',
  'strip',
  'with',
]);

const ALL_GENERATED_SCHEMA_METHODS = [
  ...GENERATED_ZOD_TYPE_METHODS,
  ...GENERATED_ZOD_OBJECT_METHODS,
];
const DERIVED_OBJECT_MODE_METHODS = ['loose', 'strict'].filter((methodName) =>
  GENERATED_ZOD_OBJECT_METHODS.includes(methodName as any),
);
const DERIVED_WRAPPER_METHODS = ALL_GENERATED_SCHEMA_METHODS.filter(
  (methodName) =>
    !SUPPORTED_CHAIN_CHECK_METHODS.has(methodName) &&
    !NON_WRAPPER_SCHEMA_METHODS.has(methodName) &&
    !DERIVED_OBJECT_MODE_METHODS.includes(methodName),
);

export const WRAPPER_METHODS = DERIVED_WRAPPER_METHODS;
export const STANDALONE_WRAPPER_METHODS = DERIVED_WRAPPER_METHODS;

export const FUNCTIONAL_CHECK_METHODS = ['email', 'url', 'ipv4', 'ipv6'];
export const PASSTHROUGH_METHODS = [
  'parse',
  'parseAsync',
  'safeParse',
  'safeParseAsync',
  'decode',
  'decodeAsync',
  'safeDecode',
  'safeDecodeAsync',
  'encode',
  'encodeAsync',
  'safeEncode',
  'safeEncodeAsync',
  'clone',
  'merge',
  'keyof',
  'safeExtend',
  'nonoptional',
  'check',
  'apply',
];
export const OBJECT_MODE_METHODS = DERIVED_OBJECT_MODE_METHODS;

export const ZOD_SCHEMA_CONTEXT_METHODS = [
  'object',
  'looseObject',
  'strictObject',
  'array',
  'union',
  'intersection',
  'discriminatedUnion',
  'record',
  'map',
  'set',
  'tuple',
  'promise',
  'optional',
  'nullable',
  'nullish',
  '_default',
  'prefault',
  'catch',
  'catchall',
  'extend',
  'partial',
  'required',
  'pipe',
  'readonly',
];
