export const ZOD_MINI_METHODS: Record<string, string> = {
  optional: 'optional',
  nullable: 'nullable',
  nullish: 'nullish',
  string: 'string',
  stringbool: 'stringbool',
  number: 'number',
  bigint: 'bigint',
  boolean: 'boolean',
  symbol: 'symbol',
  object: 'object',
  array: 'array',
  min: 'minLength',
  max: 'maxLength',
  lt: 'lt',
  lte: 'lte',
  maximum: 'maximum',
  gt: 'gt',
  gte: 'gte',
  minimum: 'minimum',
  length: 'length',
  trim: 'trim',
  email: 'email',
  url: 'url',
  ipv4: 'ipv4',
  ipv6: 'ipv6',
  uuid: 'uuid',
  int: 'int',
  negative: 'negative',
  nonpositive: 'nonpositive',
  nonnegative: 'nonnegative',
  multipleOf: 'multipleOf',
  step: 'multipleOf',
  maxSize: 'maxSize',
  minSize: 'minSize',
  size: 'size',
  maxLength: 'maxLength',
  minLength: 'minLength',
  regex: 'regex',
  lowercase: 'lowercase',
  uppercase: 'uppercase',
  includes: 'includes',
  startsWith: 'startsWith',
  endsWith: 'endsWith',
  property: 'property',
  mime: 'mime',
  literal: 'literal',
  enum: 'enum',
  nativeEnum: 'nativeEnum',
  union: 'union',
  or: 'union',
  intersection: 'intersection',
  and: 'intersection',
  extend: 'extend',
  omit: 'omit',
  pick: 'pick',
  discriminatedUnion: 'discriminatedUnion',
  partial: 'partial',
  record: 'record',
  map: 'map',
  set: 'set',
  tuple: 'tuple',
  promise: 'promise',
  date: 'date',
  undefined: 'undefined',
  null: 'null',
  void: 'void',
  any: 'any',
  unknown: 'unknown',
  never: 'never',
  nan: 'nan',
  default: '_default',
  prefault: 'prefault',
  describe: 'describe',
  brand: 'brand',
  readonly: 'readonly',
  catch: 'catch',
  catchall: 'catchall',
  pipe: 'pipe',
  transform: 'transform',
  refine: 'refine',
  superRefine: 'superRefine',
  overwrite: 'overwrite',
  normalize: 'normalize',
  toLowerCase: 'toLowerCase',
  toUpperCase: 'toUpperCase',
  meta: 'meta',
  positive: 'positive',
  required: 'required',
};

export const CHECK_METHODS = [
  'min',
  'max',
  'lt',
  'lte',
  'maximum',
  'gt',
  'gte',
  'minimum',
  'length',
  'trim',
  'email',
  'url',
  'ipv4',
  'ipv6',
  'uuid',
  'int',
  'toLowerCase',
  'toUpperCase',
  'startsWith',
  'endsWith',
  'includes',
  'regex',
  'date',
  'iso',
  'positive',
  'negative',
  'nonpositive',
  'nonnegative',
  'multipleOf',
  'step',
  'maxSize',
  'minSize',
  'size',
  'maxLength',
  'minLength',
  'lowercase',
  'uppercase',
  'property',
  'mime',
  'refine',
  'superRefine',
  'nonempty',
  'overwrite',
  'normalize',
  'meta',
  'describe',
  'discriminatedUnion',
];

export const BASE_METHODS = [
  'string',
  'stringbool',
  'number',
  'bigint',
  'boolean',
  'symbol',
  'object',
  'looseObject',
  'strictObject',
  'array',
  'pipe',
  'literal',
  'enum',
  'nativeEnum',
  'union',
  'intersection',
  'record',
  'map',
  'set',
  'tuple',
  'promise',
  'date',
  'undefined',
  'null',
  'void',
  'any',
  'unknown',
  'never',
  'nan',
  'email',
  'url',
  'ipv4',
  'ipv6',
  'discriminatedUnion',
  'optional',
  'nullable',
  'nullish',
  '_default',
  'prefault',
  'catch',
  'catchall',
  'partial',
  'required',
  'readonly',
  'extend',
  'omit',
  'pick',
];

export const WRAPPER_METHODS = [
  'optional',
  'nullable',
  'nullish',
  'transform',
  'default',
  'prefault',
  'catch',
  'catchall',
  'required',
  'array',
  'pipe',
  'readonly',
  'brand',
  'or',
  'and',
  'extend',
  'omit',
  'pick',
  'partial',
];

export const STANDALONE_WRAPPER_METHODS = [
  'optional',
  'nullable',
  'nullish',
  'partial',
  'transform',
  'default',
  'prefault',
  'catch',
  'catchall',
  'required',
  'array',
  'pipe',
  'readonly',
  'brand',
  'or',
  'and',
  'extend',
  'omit',
  'pick',
];

export const FUNCTIONAL_CHECK_METHODS = ['email', 'url', 'ipv4', 'ipv6'];
export const PASSTHROUGH_METHODS = ['parse', 'check', 'apply'];
export const OBJECT_MODE_METHODS = ['loose', 'strict', 'strip'];

export const ZOD_SCHEMA_CONTEXT_METHODS = [
  'object',
  'looseObject',
  'strictObject',
  'array',
  'union',
  'intersection',
  'discriminatedUnion',
  'record',
  'map',
  'set',
  'tuple',
  'promise',
  'optional',
  'nullable',
  'nullish',
  '_default',
  'prefault',
  'catch',
  'catchall',
  'extend',
  'partial',
  'required',
  'pipe',
  'readonly',
];
